### ISSUE TITLE
Allow re-sending the verify your account email

### ISSUE THREAD

**Issue by mphasize** [DigitalProductschool/sir-certificates#39]
Problem: Just managed to kick myself out of admin rights and tried a different login but didn't realized that it hadn't been verified yet.

Maybe admin user overview should also show which emails are verified.

```[tasklist]
### Tasks
- [ ] When login erros with "Please verify email" allow to re-send the email verification request
- [ ] When users are invited as admins, automatically set email as verified
- [ ] In superadmin view of users, show which emails have been verified
```
